[project]
name = "viking-file"
version = "0.1.0"
description = "API Wrapper for ViKiNG FiLE API (https://vikingfile.com)"
requires-python = ">=3.10"
dependencies = [
    "aiofiles>=24.1.0",
    "aiohttp>=3.12.15",
]
